name: pr

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
      deps: ${{ steps.filter.outputs.deps }}
      publish: ${{ steps.filter.outputs.publish }}
      workflows: ${{ steps.filter.outputs.workflows }}
      yml: ${{ steps.filter.outputs.yml }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - "src/**"
              - "**/*.rs"
              - Cargo.*
              - clippy.toml
              - rust-toolchain.toml
              - ".github/actions/**/*.yml"
              - ".github/workflows/pr.yml"
            deps:
              - "Cargo.toml"
              - "Cargo.lock"
              - "deny.toml"
              - ".github/workflows/pr.yml"
            publish:
              - "Cargo.toml"
              - ".github/workflows/pr.yml"
            workflows:
              - ".github/**/*.yml"
            yml:
              - "**.yml"
              - "**.yaml"

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        features:
          - name: "default"
            flags: ""
            install_sound_deps: true
          - name: "no-sound"
            flags: "--no-default-features"
            install_sound_deps: false
    name: lint-${{ matrix.features.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        if: matrix.features.install_sound_deps
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Lint (${{ matrix.features.name }})
        run: cargo clippy --all-targets ${{ matrix.features.flags }}

  build:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        features:
          - name: "default"
            flags: ""
            install_sound_deps: true
          - name: "no-sound"
            flags: "--no-default-features"
            install_sound_deps: false
    name: build-${{ matrix.os }}-${{ matrix.features.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest' && matrix.features.install_sound_deps
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build (${{ matrix.features.name }})
        run: cargo build ${{ matrix.features.flags }}

  test:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        features:
          - name: "default"
            flags: ""
            install_sound_deps: true
          - name: "no-sound"
            flags: "--no-default-features"
            install_sound_deps: false
    name: test-${{ matrix.os }}-${{ matrix.features.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest' && matrix.features.install_sound_deps
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install nextest
        uses: taiki-e/install-action@a416ddeedbd372e614cc1386e8b642692f66865e # v2.57.1
        with:
          tool: cargo-nextest
      - name: Run tests (${{ matrix.features.name }})
        env:
          RUST_BACKTRACE: 0
        run: cargo nextest run ${{ matrix.features.flags }}

  lint-yaml:
    needs: changes
    if: ${{ needs.changes.outputs.yml == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dhth/composite-actions/.github/actions/lint-yaml@main

  lint-workflows:
    needs: changes
    if: ${{ needs.changes.outputs.workflows == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dhth/composite-actions/.github/actions/lint-actions@main

  dstlled-diff:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: get-dstlled-diff
        uses: dhth/dstlled-diff-action@0ab616345f8816e9046fdefec81b14ada815aaca # v0.2.0
        with:
          pattern: '**.rs'
          starting-commit: ${{ github.event.pull_request.base.sha }}
          ending-commit: ${{ github.event.pull_request.head.sha }}
          post-comment-on-pr: 'true'

  audit:
    needs: changes
    if: ${{ needs.changes.outputs.deps == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-deny
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: EmbarkStudios/cargo-deny
      - name: cargo deny
        run: cargo deny check

  publish-check:
    needs: changes
    if: ${{ needs.changes.outputs.publish == 'true' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: cargo publish check
        run: cargo publish --dry-run
