name: publish-crates

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  publish-crates:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Publish
        run: |
          cargo publish --token "${CRATES_TOKEN}"
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
